# VIM::Packager::MakeMaker
#
# This Makefile is generated by VIM::Packager::MakeMaker version $VERSION from
# the contents of META . don't edit this file, edit META file instead.
#
# Author: Cornelius
# Email : cornelius.howl@gmail.com
# 




# -------- meta section ------
REPOSITORY = http://github.com/c9s/perl-completion.vim
VERSION = 1.71
NAME = perl-completion.vim
AUTHOR = Cornelius
VERSION_FROM = vimlib/ftplugin/perl/perlomni.vim
TYPE = plugin
SCRIPT_ID = 2852
DISTNAME = perl-completion-vim-1.71
VIM_VERSION = 7.0




# -------- config section ------
CHMOD = chmod
CP = cp
ECHO = echo
ECHO_N = echo -n
FALSE = false
FIRST_MAKEFILE = Makefile
FULLPERL = /opt/local/bin/perl
LN_S = ln -sv
LN_SF = ln -svf
MAKEFILE_OLD = Makefile.old
META_FILE = VIMMETA
MV = mv
NOECHO = @
NOOP = $(TRUE)
PERLFLAGS =  -Ilib 
PWD = `pwd`
README =  README.mkd
RM_F = rm -vf
RM_RF = rm -rf
TAR = COPY_EXTENDED_ATTRIBUTES_DISABLE=1 COPYFILE_DISABLE=1 tar
TARFLAGS = cvzf
TEST_F = test -f
TOUCH = touch
TRUE = true
VIM_AFTERBASE_DIR = /Users/c9s/.vim/after
VIM_AFTER_AFTER_DIR = /Users/c9s/.vim/after
VIM_AFTER_AUTOLOAD_DIR = /Users/c9s/.vim/autoload
VIM_AFTER_COLORS_DIR = /Users/c9s/.vim/colors
VIM_AFTER_COMPILER_DIR = /Users/c9s/.vim/compiler
VIM_AFTER_DIR = /Users/c9s/.vim/after
VIM_AFTER_DOC_DIR = /Users/c9s/.vim/doc
VIM_AFTER_FTDETECT_DIR = /Users/c9s/.vim/ftdetect
VIM_AFTER_FTPLUGIN_DIR = /Users/c9s/.vim/ftplugin
VIM_AFTER_MACROS_DIR = /Users/c9s/.vim/macros
VIM_AFTER_PLUGIN_DIR = /Users/c9s/.vim/plugin
VIM_AFTER_SYNTAX_DIR = /Users/c9s/.vim/syntax
VIM_AUTOLOAD_DIR = /Users/c9s/.vim/autoload
VIM_BASEDIR = /Users/c9s/.vim
VIM_COLORS_DIR = /Users/c9s/.vim/colors
VIM_COMPILER_DIR = /Users/c9s/.vim/compiler
VIM_DOC_DIR = /Users/c9s/.vim/doc
VIM_FTDETECT_DIR = /Users/c9s/.vim/ftdetect
VIM_FTPLUGIN_DIR = /Users/c9s/.vim/ftplugin
VIM_MACROS_DIR = /Users/c9s/.vim/macros
VIM_PLUGIN_DIR = /Users/c9s/.vim/plugin
VIM_SYNTAX_DIR = /Users/c9s/.vim/syntax




# -------- file section ------
VIMLIB = vimlib
VIMMETA = VIMMETA
TO_INST_VIMS = vimlib/ftplugin/perl/perlomni.vim \
	vimlib/ftplugin/perl/perl-completion.vim
VIMS_TO_RUNT = vimlib/ftplugin/perl/perlomni.vim \
	$(VIM_BASEDIR)/ftplugin/perl/perlomni.vim \
	vimlib/ftplugin/perl/perl-completion.vim \
	$(VIM_BASEDIR)/ftplugin/perl/perl-completion.vim
TO_INST_BIN = utils/parse_moose_accessor.pl \
	utils/perl_function_list.pl \
	utils/find_base_classes.pl \
	utils/moose-type-constraints
BIN_TO_RUNT = utils/parse_moose_accessor.pl \
	$(VIM_BASEDIR)/bin/parse_moose_accessor.pl \
	utils/perl_function_list.pl \
	$(VIM_BASEDIR)/bin/perl_function_list.pl \
	utils/find_base_classes.pl \
	$(VIM_BASEDIR)/bin/find_base_classes.pl \
	utils/moose-type-constraints \
	$(VIM_BASEDIR)/bin/moose-type-constraints




# -------- main section ------
.PHONY: all install clean uninstall help upload link

all : install-deps
		$(NOECHO) $(NOOP)

install : pure_install install-deps
		$(NOECHO) $(NOOP)

pure_install : 
		$(NOECHO) $(FULLPERL) $(PERLFLAGS) -MVIM::Packager::Installer=install -e 'install()' $(NAME) $(VIMS_TO_RUNT) $(BIN_TO_RUNT)

install-deps : 
		$(NOECHO) $(FULLPERL) $(PERLFLAGS) -MVIM::Packager::Installer=install_deps_remote  -e 'install_deps_remote()' libperl.vim  \
	autoload/libperl.vim \
	http://github.com/c9s/libperl.vim/raw/master/vimlib/autoload/libperl.vim
		$(NOECHO) $(FULLPERL) $(PERLFLAGS) -MVIM::Packager::Installer=install_deps_remote  -e 'install_deps_remote()' search-window.vim  \
	autoload/swindow.vim \
	http://github.com/c9s/search-window.vim/raw/master/vimlib/autoload/swindow.vim

link : 
		$(NOECHO) $(LN_S) $(PWD)/vimlib/ftplugin/perl/perlomni.vim $(VIM_BASEDIR)/ftplugin/perl/perlomni.vim
		$(NOECHO) $(LN_S) $(PWD)/vimlib/ftplugin/perl/perl-completion.vim $(VIM_BASEDIR)/ftplugin/perl/perl-completion.vim

link-force : 
		$(NOECHO) $(LN_SF) $(PWD)/vimlib/ftplugin/perl/perlomni.vim $(VIM_BASEDIR)/ftplugin/perl/perlomni.vim
		$(NOECHO) $(LN_SF) $(PWD)/vimlib/ftplugin/perl/perl-completion.vim $(VIM_BASEDIR)/ftplugin/perl/perl-completion.vim

unlink : 
		$(NOECHO) $(RM) $(VIM_BASEDIR)/ftplugin/perl/perlomni.vim
		$(NOECHO) $(RM) $(VIM_BASEDIR)/ftplugin/perl/perl-completion.vim

manifest : 
		$(NOECHO) $(ECHO) ".git" > MANIFEST.SKIP
		$(NOECHO) $(ECHO) ".svn" >> MANIFEST.SKIP
		$(NOECHO) $(ECHO) ".*.tar.gz" >> MANIFEST.SKIP
		$(FULLPERL) $(PERLFLAGS) -MVIM::Packager::Manifest=mkmanifest -e 'mkmanifest'

dist : manifest
		$(TAR) $(TARFLAGS) $(DISTNAME).tar.gz $(TO_INST_VIMS) $(META_FILE) $(README) `cat MANIFEST`
		$(NOECHO) $(NOOP)

help : 
		perldoc VIM::Packager

uninstall : 
		$(NOECHO) $(FULLPERL) $(PERLFLAGS) -MVIM::Packager::Installer=uninstall   -e 'uninstall()' $(NAME)

reinstall : uninstall install
		$(NOECHO) $(NOOP)

upload : dist
		$(FULLPERL) $(PERLFLAGS) -MVIM::Packager::Uploader=upload -e 'upload()' $(PWD)/$(DISTNAME).tar.gz \
	$(VIM_VERSION) \
	$(VERSION) \
	$(SCRIPT_ID)

clean : 
		$(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
		$(RM) *.tar.gz

bump : 
		$(NOECHO) $(FULLPERL) $(PERLFLAGS) -MVIM::Packager::Installer=bump_version -e 'bump_version()' 
		sh -c 'vim-packager build'
		sh -c 'make upload'

release : bump
		$(NOECHO) $(NOOP)

